export const LOAD_CONTENT= "LOAD_CONTENT";
export const GET_CONTENT= "GET_CONTENT";
export const READ_CONTENT= "READ_CONTENT";
export const ADD_CONTENT= "ADD_CONTENT";
export const DELETE_CONTENT= "DELETE_CONTENT";
export const UPDATE_CONTENT= "UPDATE_CONTENT";